import { useRouter } from 'next/router'
import React, { useEffect, useState } from 'react'
import Zoom from "react-medium-image-zoom";
import "react-medium-image-zoom/dist/styles.css";
import axios from "axios";
import styles from '../../styles/card.module.css'
import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.css'

export default function Student() {

    const [students, setStudents] = useState([])
    
    const router = useRouter()
    console.log(router.query)

    useEffect(() => {
        axios
            .get(` https://fejs-c7-api.herokuapp.com/api/students/${router.query.id}?populate=*`)
            .then((res) => {
                setStudents([res.data.data])
            })
    })

    return (
      <div>
        <Head>
          <title>Detail</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      <div>
      <div className={styles.card}>
        <div className={styles.wrapper}>
      {students.map((student) => {
        return(
          <div key={student.id} style={{width:'300px'}} className="m-5">
                <div className='border rounded border-success'>
                { student.attributes.photo.data !== null &&
                      <Zoom>
                        <img className="card-img-top rounded" src={student.attributes.photo.data.attributes.url} style={{width:"300px", height:"400px"}} />
                      </Zoom>
                    }
                    <div className="card-body">
                      <p className="card-text">First Name: {student.attributes.firstname}</p>
                      <p className="card-text">Last Name: {student.attributes.lastname}</p>
                      <p className="card-text">Location: {student.attributes.location}</p>
                    </div>
              </div>
            </div>
        )
    })}
    </div>
    </div>
    </div>
    </div>
    )
}
