import React from 'react'
import Head from 'next/head'
import { Button } from 'react-bootstrap'
import styles from "../styles/input.module.css"

export default function input() {
  return (
    <div className={styles.input}>
        <Head>
            <title>Input</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.inputForm}>
            <h2 style={{textAlign: "center"}}>Input Page</h2>
            <form action="/" method="post" className={styles.form}>
                <label>Name</label>
                <input type="text" id="name" name="name" />
                <label>Age</label>
                <input type="number" id="age" name="age" />
                <label>Email</label>
                <input type="text" id="email" name="email" />
                <Button type="submit" className={styles.btn}>Submit Form</Button>
            </form>
        </div>
    </div>
  )
}
