import React from 'react'
import Head from 'next/head'
import { Button } from 'react-bootstrap'
import styles from "../styles/input.module.css"
import { useRef } from 'react'
import axios from 'axios'


export default function input() {


  const inputFirstname =useRef();
  const inputLastname = useRef();
  const inputLocation = useRef();
  const inputPhoto = useRef();
  const handleSubmit = async (event) => {
    event.preventDefault();
    const user ={
      firstname:inputFirstname.current.value,
      lastname:inputLastname.current.value,
      location:inputLocation.current.value
    }
    // console.log(user)
    console.log(inputPhoto.current.files);
    const formData = new FormData();
    formData.append('data', JSON.stringify(user))
    Array.from(inputPhoto.current.files).forEach(file=>{
      formData.append('files.photo',file,file.name)
    })
    const res = await 
    axios.post('https://fejs-c7-api.herokuapp.com/api/students/',formData)
    console.log(res.data)
    
    };
  return (
    <div className={styles.input}>
        <Head>
            <title>Input</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.inputForm}>
            <h2 style={{textAlign: "center"}}>Input Page</h2>
            <form onSubmit={handleSubmit} action="/" method="post" className={styles.form}>
                <label>First Name</label>
                <input type="text" id="firstname" name="firstname" ref={inputFirstname} />
                <label>Last Name</label>
                <input type="text" id="lastname" name="lastname" ref={inputLastname} />
                <label>Location</label>
                <input type="text" id="location" name="location" ref={inputLocation}/>
                <label>Photo</label>
                <input type="file" id="photo" name="photo" ref={inputPhoto}/>
                <input type="submit" className={styles.btn} value="SUBMIT FORM" />
            </form>
        </div>
    </div>
  )
}

// import React, {useRef as useRef} from 'react'
// import Head from 'next/head'
// import { Button } from 'react-bootstrap'
// import styles from "../styles/input.module.css"
// import axios from 'axios'
// import {useDropzone} from 'react-dropzone'

// export default function input() {
  
//   const { acceptedFiles, getRootProps, getInputProps } = useDropzone();
//   const files = acceptedFiles.map((file) => (
//     <li key={file.path}>
//       {file.path} - {file.size} bytes
//     </li>
//   ));

//   const inputFirstname = useRef("");
//   const inputLastname = useRef("");
//   const inputLocation = useRef("");
//   const inputPhoto = useRef("");

//   const formSubmitHandler = async (event) => {
//     event.preventDefault();
//     const submittedData = {
//       firstname: inputFirstname.current.value,
//       lastname: inputLastname.current.value,
//       location: inputLocation.current.value,
//     };

//   const formData = new FormData();

//   formData.append("data", JSON.stringify(submittedData));
//   acceptedFiles.forEach((file) => {
//     formData.append("files.photo", file, file.path);
//   });  

//   const res = await axios.post(
//     "https://fejs-c7-api.herokuapp.com/api/students/",
//     formData
//   );
//   console.log(res.data);
// };
  
//   return (
//     <div className={styles.input}>
//         <Head>
//             <title>Input</title>
//             <meta name="description" content="Generated by create next app" />
//             <link rel="icon" href="/favicon.ico" />
//         </Head>
//         <div className={styles.inputForm}>
//             <h2 style={{textAlign: "center"}}>Input Page</h2>
//             <form onSubmit={formSubmitHandler} className={styles.form}>
//                   <label>First Name</label>
//                   <input type="text" id="firstname" name="firstname" inputRef={inputFirstname} required />
//                   <label>Last Name</label>
//                   <input type="text" id="lastname" name="lastname" inputRef={inputLastname} required/>
//                   <label>Location</label>
//                   <input type="text" id="location" name="location" inputRef={inputLocation} required/>
//                   <label>Photo</label>
//                   <div {...getRootProps({className: "dropzone"})}>
//                     <input {...getInputProps()}></input>
//                     <p>Click to select files</p>
//                   </div>
//                   <ul>{files}</ul>
//                 <Button type="submit" value={"SUBMIT FORM"} className={styles.btn}>Submit Form</Button>
//             </form>
//         </div>
//     </div>
//   )
// }


